-- Content production pipeline tables. Three additions:
--
-- 1. url_gap_runs / url_gap_keywords — pasted competitor URL → DFS
--    returns every query that page ranks for in the top 100 → we cross-
--    reference against the client's own ranks. AM gets a precise list
--    of sub-topics to cover to outrank that specific page.
--
-- 2. content_drafts — full posts generated by Claude from an existing
--    Plan brief (PlanningTab). Brand-aware: the prompt reads the
--    client's brand_assets + briefing_field so tone is bespoke. Stored
--    as markdown (source of truth) plus rendered HTML so the publisher
--    can push either format depending on the platform.
--
-- 3. content_publications — record of a draft pushed to a destination
--    (wordpress, shopify, exported_clipboard, exported_docx). Includes
--    scheduled_at for cron-driven future publishes, and external_url so
--    the AM can jump to the live post once it's up.

-- ── 1. URL gap simulator ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS url_gap_runs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  client_id UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  competitor_url TEXT NOT NULL,
  location_code INT NOT NULL DEFAULT 2826,
  page_keyword_count INT NOT NULL DEFAULT 0,    -- queries that page ranks for
  gap_count INT NOT NULL DEFAULT 0,             -- queries client doesn't rank top-10 for
  summary_md TEXT,                              -- Claude's plain-English angle list
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_url_gap_runs_client
  ON url_gap_runs(client_id, created_at DESC);

CREATE TABLE IF NOT EXISTS url_gap_keywords (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  run_id UUID NOT NULL REFERENCES url_gap_runs(id) ON DELETE CASCADE,
  keyword TEXT NOT NULL,
  search_volume INT,
  competitor_position INT,
  client_position INT,                          -- null = not in top 100
  is_gap BOOLEAN NOT NULL DEFAULT FALSE,        -- TRUE when competitor ranks + client doesn't
  position_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_url_gap_keywords_run
  ON url_gap_keywords(run_id, position_order);

-- ── 2. Content drafts ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS content_drafts (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  client_id UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  target_keyword TEXT,
  brief_json JSONB,                             -- the PlanningTab brief used as input
  title TEXT,
  meta_description TEXT,
  body_markdown TEXT,                           -- source of truth, AM-editable
  body_html TEXT,                               -- rendered for HTML-native platforms
  word_count INT,
  status VARCHAR(20) NOT NULL DEFAULT 'draft',  -- draft | approved | published | archived
  brand_voice_hash VARCHAR(64),                 -- so we can flag when brand assets changed since draft
  claude_model VARCHAR(64),
  tokens_used INT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_content_drafts_client
  ON content_drafts(client_id, created_at DESC);

-- ── 3. Content publications ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS content_publications (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  draft_id UUID NOT NULL REFERENCES content_drafts(id) ON DELETE CASCADE,
  platform VARCHAR(32) NOT NULL,                -- wordpress | shopify | clipboard | docx
  platform_post_id TEXT,                        -- external ID once published
  status VARCHAR(20) NOT NULL DEFAULT 'queued', -- queued | publishing | published | failed | scheduled
  scheduled_at TIMESTAMPTZ,                     -- future-publish target
  published_at TIMESTAMPTZ,
  external_url TEXT,                            -- live post URL once posted
  error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_content_publications_draft
  ON content_publications(draft_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_content_publications_scheduled
  ON content_publications(scheduled_at)
  WHERE status = 'scheduled';

-- ── 4. Backlink prospects ────────────────────────────────────────────────
-- "Automated backlinks" reframed safely: scrape competitor backlinks via
-- DFS, score for relevance and DA, push the best into the existing
-- Outreach engine as a campaign. The link is then EARNED through a real
-- pitch — no purchased / network links. Pre-1-July the table is empty
-- because the DFS Backlinks endpoint is still gated.
CREATE TABLE IF NOT EXISTS backlink_prospects (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  client_id UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  source_domain VARCHAR(255) NOT NULL,
  source_url TEXT,
  source_page_title TEXT,
  competitor_domain VARCHAR(255),               -- which competitor we found this link on
  domain_rank INT,                              -- DFS rank 0-1000
  relevance_score INT,                          -- 0-100, our composite
  tactic VARCHAR(32) NOT NULL DEFAULT 'competitor_link',
                                                -- competitor_link | broken_link | digital_pr | data_pr
  status VARCHAR(20) NOT NULL DEFAULT 'new',    -- new | added_to_outreach | won | rejected
  outreach_contact_id UUID REFERENCES outreach_contacts(id) ON DELETE SET NULL,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_backlink_prospects_client
  ON backlink_prospects(client_id, status, relevance_score DESC);

CREATE UNIQUE INDEX IF NOT EXISTS uq_backlink_prospects_dedupe
  ON backlink_prospects(client_id, source_domain, COALESCE(source_url, ''));
