-- Richer, more visual client strategies. Beyond the SOSTAC checklist (phases),
-- a tailored strategy now carries a structured "profile" — narrative exec
-- summary, personas, SWOT, a functional/emotional/situational competitor map,
-- and quantified objectives — modelled on October's hand-written agency
-- strategies. Generated by the Claude tailor step; rendered as cards/grids.
ALTER TABLE client_strategy ADD COLUMN IF NOT EXISTS profile JSONB;
