// Walks a report template (see reportTemplate.js) section by section and
// returns "resolved sections" — plain data objects ready for pdfService to
// render. Each resolved section keeps its template id + type + title and
// adds the type-specific payload (cells, tables, chart, text).
//
// Narrative sections are generated by Claude here too — one prompt per
// section, given that section's per-source data slice + the client briefing
// + the monthly focus. Sections run sequentially because their prompts are
// short; parallelising adds complexity without much wall-clock saving.

const claudeService = require('./claude');
const tpl = require('./reportTemplate');

const SYSTEM_PROMPT = 'You are a performance marketing analyst writing reports for October Communications, a marketing agency. Write clearly, commercially, without filler or generic language. British English. No hype. Your output will be sent directly to clients.';

async function resolveTemplate({ template, client, period, periodStart, periodEnd, rawData, rawDataPrev, rawDataByPeriod, seoData, chatHistory = [], narrativeCache }) {
  const resolved = [];
  for (const section of template.sections) {
    try {
      const r = await resolveSection(section, { client, period, periodStart, periodEnd, rawData, rawDataPrev, rawDataByPeriod, seoData, chatHistory, narrativeCache });
      if (r) resolved.push(r);
    } catch (err) {
      console.error(`[templateRenderer] section "${section.id}" failed:`, err.message);
      resolved.push({ id: section.id, type: 'error', title: section.title, message: err.message });
    }
  }

  // Annotate non-narrative sections with a one-sentence "what stands out"
  // insight from Claude. A single batched call keeps cost / latency in check.
  // Sections with `insight: false` on the template skip this pass — gives
  // the AM a per-section opt-out for the auto-generated italic line.
  try {
    const insightsAllowed = new Set(
      (template.sections || []).filter(s => s.insight !== false).map(s => s.id)
    );
    const insights = await generateSectionInsights({
      resolved: resolved.filter(s => insightsAllowed.has(s.id)),
      client, period,
    });
    for (const s of resolved) {
      if (insights[s.id]) s.insight = insights[s.id];
    }
  } catch (err) {
    console.error('[templateRenderer] insights pass failed:', err.message);
  }
  return resolved;
}

// Batch insight generator — gives each non-narrative section a single
// commercially-pointed sentence to help the reader scan the page. We send
// every section's summarised data in one prompt rather than per-section to
// keep API spend predictable and reports fast.
async function generateSectionInsights({ resolved, client, period }) {
  const candidates = resolved.filter(s => s.type !== 'narrative' && s.type !== 'error' && hasContent(s));
  if (!candidates.length) return {};
  const summarised = candidates.map(s => ({ id: s.id, title: s.title, type: s.type, data: insightPayload(s) }));
  const prompt = `Client: ${client.name}
Period: ${period}

For each section below, write ONE plain-English sentence that tells the reader what's notable — pick out the biggest number, the biggest mover, or the most actionable point. Be specific (include figures), commercial in tone, British English, no filler.

Sections:
${JSON.stringify(summarised, null, 2)}

Return ONLY a JSON object mapping section id → sentence. Example:
{ "ecom_summary": "Combined B2C revenue hit £24,674 across 150 orders, with the US store contributing 73% on a £223 AOV.", "google_ads": "Both Google Ads markets returned positive ROAS, UK at 6.85× outpacing US at 6.61×." }`;
  const reply = await claudeService.callClaude({ max_tokens: 1024, system: SYSTEM_PROMPT, user: prompt });
  try {
    const cleaned = reply.replace(/^```(?:json)?\s*/i, '').replace(/```\s*$/, '').trim();
    return JSON.parse(cleaned);
  } catch {
    return {};
  }
}

function hasContent(s) {
  if (s.type === 'metrics_grid') return (s.cells?.length || s.rows?.length);
  if (s.type === 'tables') return s.tables?.length;
  if (s.type === 'bar_chart') return s.chart?.data?.length;
  if (s.type === 'position_distribution') return s.rankings?.length;
  return false;
}

// A compact shape per section for the insights prompt — enough for Claude to
// reason about without shipping the full payload.
function insightPayload(s) {
  if (s.type === 'metrics_grid') {
    if (s.layout === 'table') return { metricLabels: s.metricLabels, rows: s.rows };
    return { cells: (s.cells || []).slice(0, 12) };
  }
  if (s.type === 'tables') return (s.tables || []).map(t => ({ heading: t.heading, headers: t.headers, rows: (t.rows || []).slice(0, 10) }));
  if (s.type === 'bar_chart') return s.chart?.data || [];
  if (s.type === 'position_distribution') {
    const counts = { top3: 0, '4-10': 0, '11-20': 0, '21-50': 0, '51-100': 0, '100+': 0 };
    for (const k of (s.rankings || [])) {
      const p = parseInt(k.current_position);
      if (!p) continue;
      if (p <= 3) counts.top3++;
      else if (p <= 10) counts['4-10']++;
      else if (p <= 20) counts['11-20']++;
      else if (p <= 50) counts['21-50']++;
      else if (p <= 100) counts['51-100']++;
      else counts['100+']++;
    }
    return counts;
  }
  return null;
}

async function resolveSection(section, ctx) {
  switch (section.type) {
    case 'narrative':           return resolveNarrative(section, ctx);
    case 'metrics_grid':        return resolveMetricsGrid(section, ctx);
    case 'connector_table':     return resolveConnectorTable(section, ctx);
    case 'bar_chart':           return resolveBarChart(section, ctx);
    case 'position_distribution': return resolvePositionDistribution(section, ctx);
    default:
      throw new Error(`Unknown section type "${section.type}"`);
  }
}

async function resolveNarrative(section, { client, period, rawData, seoData, chatHistory, narrativeCache }) {
  // Slice the data down to just what this section references; passing the
  // whole rawData blows up token budgets and dilutes Claude's focus.
  const matches = tpl.matchSources(rawData, section.sources || ['*']);
  const condensed = matches.map(m => ({
    connector: m.type,
    store: m.storeLabel || undefined,
    metrics: previewMetrics(m),
  }));
  const seoBlock = (seoData?.rankings || []).length
    ? `\nSEO rankings: ${seoData.rankings.length} keywords tracked. Top 5 by position: ${[...seoData.rankings].filter(k => k.current_position).sort((a, b) => a.current_position - b.current_position).slice(0, 5).map(k => `${k.keyword} (pos ${k.current_position})`).join(', ')}.`
    : '';
  const chat = (chatHistory || []).slice(-10).map(m => `${m.role === 'user' ? 'AM' : 'Analyst'}: ${m.content}`).join('\n');

  const userPrompt = `Client: ${client.name}
About: ${client.briefing_field || '(no briefing set)'}
Period: ${period}
Monthly focus: ${client.monthly_focus || '(none set)'}

Data slice for this section:
${JSON.stringify(condensed, null, 2)}${seoBlock}

${chat ? `\nRecent account-manager conversations:\n${chat}\n` : ''}
Section instruction:
${section.prompt || 'Summarise the data above in 2-3 sentences.'}

Length: ${section.id === 'exec_summary' ? 'maximum 120 words' : 'maximum 60 words — two or three short sentences'}. Be concise. Lead with the single most important point. No filler, no hedging, no restating what's in the table headers.

Strict rules on numbers:
- Quote only figures that appear in the "Data slice for this section" block above. If a number isn't in that block, do not write it.
- Do not invent year-on-year comparisons by treating prior-year totals as "the equivalent period" — when you only have one period of data, just describe that period. Don't make up "vs last year" framings.
- Do not infer trends across years unless the slice explicitly gives you matching windows (e.g. YTD vs YTD).
- It's better to write nothing than to write a misleading comparison.

Respond with just the paragraph(s) — prose only. No preamble, no heading, no markdown tables (lines of pipes/dashes are rendered as raw text, not parsed as a table), no bullet lists, no numbered lists, no code blocks. If you need to reference numbers, put them inline in sentences. If a data table is needed, it belongs in a separate metrics_grid section, not in narrative prose.`;

  // Preview path: re-use a previously generated paragraph when the inputs
  // that affect it (prompt, sources, data slice, period) haven't changed.
  // The full report path passes no narrativeCache and always re-prompts.
  let cacheKey = null;
  if (narrativeCache) {
    cacheKey = narrativeCache.keyFor(section, condensed, period);
    const cached = narrativeCache.get(cacheKey);
    if (cached) return { id: section.id, type: 'narrative', title: section.title, text: cached, cached: true };
  }

  const msg = await claudeService.callClaude({
    // Word caps above translate to roughly 200 / 100 tokens. Keep some
    // headroom so a tight 120-word executive summary isn't truncated.
    max_tokens: section.id === 'exec_summary' ? 320 : 160,
    system: SYSTEM_PROMPT,
    user: userPrompt,
  });
  const text = msg.trim();
  if (cacheKey && narrativeCache) narrativeCache.set(cacheKey, text);
  return { id: section.id, type: 'narrative', title: section.title, text };
}

function previewMetrics(match) {
  // A compact view of a single source's data — enough for Claude to write
  // about it without us shipping the whole connector payload into the prompt.
  const catalog = tpl.METRIC_CATALOG[match.type] || {};
  const out = {};
  for (const [k, def] of Object.entries(catalog)) {
    try { out[k] = def.get(match.data); } catch { /* swallow per-metric extraction errors */ }
  }
  return out;
}

function resolveMetricsGrid(section, { rawData, rawDataPrev, rawDataByPeriod, periodStart, periodEnd }) {
  const result = tpl.resolveMetricsGrid(section, rawData, rawDataPrev, { rawDataByPeriod, periodStart, periodEnd });
  return { id: section.id, type: 'metrics_grid', title: section.title, ...result };
}

function resolveConnectorTable(section, { rawData }) {
  const tables = tpl.resolveConnectorTables(section, rawData);
  return { id: section.id, type: 'tables', title: section.title, tables };
}

function resolveBarChart(section, { rawData }) {
  const chart = tpl.resolveBarChart(section, rawData);
  return { id: section.id, type: 'bar_chart', title: section.title, chart };
}

function resolvePositionDistribution(section, { seoData }) {
  return { id: section.id, type: 'position_distribution', title: section.title, rankings: seoData?.rankings || [] };
}

module.exports = { resolveTemplate };
