// Walks a report template (see reportTemplate.js) section by section and
// returns "resolved sections" — plain data objects ready for pdfService to
// render. Each resolved section keeps its template id + type + title and
// adds the type-specific payload (cells, tables, chart, text).
//
// Narrative sections are generated by Claude here too — one prompt per
// section, given that section's per-source data slice + the client briefing
// + the monthly focus. Sections run sequentially because their prompts are
// short; parallelising adds complexity without much wall-clock saving.

const claudeService = require('./claude');
const tpl = require('./reportTemplate');

const SYSTEM_PROMPT = 'You are a performance marketing analyst writing reports for October Communications, a marketing agency. Write clearly, commercially, without filler or generic language. British English. No hype. Your output will be sent directly to clients.';

async function resolveTemplate({ template, client, period, rawData, seoData, chatHistory = [] }) {
  const resolved = [];
  for (const section of template.sections) {
    try {
      const r = await resolveSection(section, { client, period, rawData, seoData, chatHistory });
      if (r) resolved.push(r);
    } catch (err) {
      console.error(`[templateRenderer] section "${section.id}" failed:`, err.message);
      resolved.push({ id: section.id, type: 'error', title: section.title, message: err.message });
    }
  }
  return resolved;
}

async function resolveSection(section, ctx) {
  switch (section.type) {
    case 'narrative':           return resolveNarrative(section, ctx);
    case 'metrics_grid':        return resolveMetricsGrid(section, ctx);
    case 'connector_table':     return resolveConnectorTable(section, ctx);
    case 'bar_chart':           return resolveBarChart(section, ctx);
    case 'position_distribution': return resolvePositionDistribution(section, ctx);
    default:
      throw new Error(`Unknown section type "${section.type}"`);
  }
}

async function resolveNarrative(section, { client, period, rawData, seoData, chatHistory }) {
  // Slice the data down to just what this section references; passing the
  // whole rawData blows up token budgets and dilutes Claude's focus.
  const matches = tpl.matchSources(rawData, section.sources || ['*']);
  const condensed = matches.map(m => ({
    connector: m.type,
    store: m.storeLabel || undefined,
    metrics: previewMetrics(m),
  }));
  const seoBlock = (seoData?.rankings || []).length
    ? `\nSEO rankings: ${seoData.rankings.length} keywords tracked. Top 5 by position: ${[...seoData.rankings].filter(k => k.current_position).sort((a, b) => a.current_position - b.current_position).slice(0, 5).map(k => `${k.keyword} (pos ${k.current_position})`).join(', ')}.`
    : '';
  const chat = (chatHistory || []).slice(-10).map(m => `${m.role === 'user' ? 'AM' : 'Analyst'}: ${m.content}`).join('\n');

  const userPrompt = `Client: ${client.name}
About: ${client.briefing_field || '(no briefing set)'}
Period: ${period}
Monthly focus: ${client.monthly_focus || '(none set)'}

Data slice for this section:
${JSON.stringify(condensed, null, 2)}${seoBlock}

${chat ? `\nRecent account-manager conversations:\n${chat}\n` : ''}
Section instruction:
${section.prompt || 'Summarise the data above in 2-3 sentences.'}

Respond with just the paragraph(s). No preamble, no heading.`;

  const msg = await claudeService.callClaude({
    max_tokens: section.id === 'exec_summary' ? 1024 : 512,
    system: SYSTEM_PROMPT,
    user: userPrompt,
  });
  return { id: section.id, type: 'narrative', title: section.title, text: msg.trim() };
}

function previewMetrics(match) {
  // A compact view of a single source's data — enough for Claude to write
  // about it without us shipping the whole connector payload into the prompt.
  const catalog = tpl.METRIC_CATALOG[match.type] || {};
  const out = {};
  for (const [k, def] of Object.entries(catalog)) {
    try { out[k] = def.get(match.data); } catch { /* swallow per-metric extraction errors */ }
  }
  return out;
}

function resolveMetricsGrid(section, { rawData }) {
  const cells = tpl.resolveMetricsGrid(section, rawData);
  return { id: section.id, type: 'metrics_grid', title: section.title, cells };
}

function resolveConnectorTable(section, { rawData }) {
  const tables = tpl.resolveConnectorTables(section, rawData);
  return { id: section.id, type: 'tables', title: section.title, tables };
}

function resolveBarChart(section, { rawData }) {
  const chart = tpl.resolveBarChart(section, rawData);
  return { id: section.id, type: 'bar_chart', title: section.title, chart };
}

function resolvePositionDistribution(section, { seoData }) {
  return { id: section.id, type: 'position_distribution', title: section.title, rankings: seoData?.rankings || [] };
}

module.exports = { resolveTemplate };
